# Generated by Django 5.2.9 on 2026-08-24 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0003_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendar',
            name='title',
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name='healthcampaign',
            name='content',
            field=models.TextField(max_length=500),
        ),
        migrations.AlterField(
            model_name='healthtips',
            name='content',
            field=models.TextField(max_length=500),
        ),
    ]
