# Generated by Django 5.2.9 on 2026-08-24 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospitalapp', '0004_alter_calendar_title_alter_healthcampaign_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='password',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='doctor',
            name='username',
            field=models.CharField(default='', max_length=50),
        ),
    ]
